
package com.lcydream.project.client.jdk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserServerImplService", targetNamespace = "http://impl.jdk.server.project.lcydream.com/", wsdlLocation = "http://127.0.0.1:8888/ws/user?wsdl")
public class UserServerImplService
    extends Service
{

    private final static URL USERSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERSERVERIMPLSERVICE_EXCEPTION;
    private final static QName USERSERVERIMPLSERVICE_QNAME = new QName("http://impl.jdk.server.project.lcydream.com/", "UserServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8888/ws/user?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSERVERIMPLSERVICE_WSDL_LOCATION = url;
        USERSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public UserServerImplService() {
        super(__getWsdlLocation(), USERSERVERIMPLSERVICE_QNAME);
    }

    public UserServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSERVERIMPLSERVICE_QNAME, features);
    }

    public UserServerImplService(URL wsdlLocation) {
        super(wsdlLocation, USERSERVERIMPLSERVICE_QNAME);
    }

    public UserServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSERVERIMPLSERVICE_QNAME, features);
    }

    public UserServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserServerImpl
     */
    @WebEndpoint(name = "UserServerImplPort")
    public UserServerImpl getUserServerImplPort() {
        return super.getPort(new QName("http://impl.jdk.server.project.lcydream.com/", "UserServerImplPort"), UserServerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServerImpl
     */
    @WebEndpoint(name = "UserServerImplPort")
    public UserServerImpl getUserServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.jdk.server.project.lcydream.com/", "UserServerImplPort"), UserServerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw USERSERVERIMPLSERVICE_EXCEPTION;
        }
        return USERSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
