
package com.lcydream.project.client.jdk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServerImpl", targetNamespace = "http://impl.jdk.server.project.lcydream.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServerImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkNickName", targetNamespace = "http://impl.jdk.server.project.lcydream.com/", className = "com.lcydream.project.client.jdk.CheckNickName")
    @ResponseWrapper(localName = "checkNickNameResponse", targetNamespace = "http://impl.jdk.server.project.lcydream.com/", className = "com.lcydream.project.client.jdk.CheckNickNameResponse")
    @Action(input = "http://impl.jdk.server.project.lcydream.com/UserServerImpl/checkNickNameRequest", output = "http://impl.jdk.server.project.lcydream.com/UserServerImpl/checkNickNameResponse")
    public String checkNickName(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
